spring:
  datasource:
    url: jdbc:h2:mem:webauthn
    driver-class-name: org.h2.Driver
    username: authn_user
    password: authn_password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  config:
    import:
      - classpath:keycloak.yml

authn:
  hostname: localhost
  display: Otka WebAuthn Sample Application
  origin: http://localhost:4200